//-----------------------------------------------------------------------------
// Copyright (c) 2014 Michael G. Brehm
// 
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
// 
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
// 
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.
//-----------------------------------------------------------------------------

import "oaidl.idl";
import "ocidl.idl";
import "wtypes.idl";

//---------------------------------------------------------------------------
// Forward Interface Declarations

interface IVmService;				// {B46E5851-24F7-4BD0-9B51-2E188C19C3C8}
interface IDevice;					// {0B1E207A-1973-4CFE-9A8E-A5FD89DA1AEB}
interface ICharacterDevice;			// {A7F26FEF-BFC9-413E-B5BC-816DE283B0E6}
interface IBlockDevice;				// {20B19DAF-0151-4D89-8DDF-07172FCD689E}

//---------------------------------------------------------------------------
// CLSID Declarations

// CLSID_VmService				--> {FD778C20-0203-4AA0-B315-2479B28946B4}
cpp_quote("DEFINE_GUID(CLSID_VmService, ")
cpp_quote("0xfd778c20, 0x203, 0x4aa0, 0xb3, 0x15, 0x24, 0x79, 0xb2, 0x89, 0x46, 0xb4);")

//---------------------------------------------------------------------------
// Type Declarations

// Redefine both LPWSTR and LPCWSTR to default to a [unique] pointer type,
// which will allow NULL pointers to be passed into remote methods

typedef [unique, string] wchar_t*			LPWSTR;
typedef [unique, string] const wchar_t*		LPCWSTR;

//---------------------------------------------------------------------------
// Interface IVmService

[
	object, nonextensible,
	uuid(B46E5851-24F7-4BD0-9B51-2E188C19C3C8),
	pointer_default(unique)
]

interface IVmService : IUnknown
{
};

//---------------------------------------------------------------------------
// Interface IDevice

[
	object, nonextensible,
	uuid(0B1E207A-1973-4CFE-9A8E-A5FD89DA1AEB),
	pointer_default(unique)
]

interface IDevice : IUnknown
{
};

//---------------------------------------------------------------------------
// Interface ICharacterDevice

[
	object, nonextensible,
	uuid(A7F26FEF-BFC9-413E-B5BC-816DE283B0E6),
	pointer_default(unique)
]

interface ICharacterDevice : IDevice
{
};

//---------------------------------------------------------------------------
// Interface IBlockDevice

[
	object, nonextensible,
	uuid(20B19DAF-0151-4D89-8DDF-07172FCD689E),
	pointer_default(unique)
]

interface IBlockDevice : IDevice
{
};

//---------------------------------------------------------------------------
