// devices.idl : IDL source for devices
//

// This file will be processed by the MIDL tool to
// produce the type library (devices.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";
import "vm.dcom.idl";

[
	object,
	uuid(72F2C5D9-7693-4CA3-894B-B501E651579F),
	pointer_default(unique)
]
interface INull : ICharacterDevice {
};
[
	uuid(778BEDC0-E88B-425F-B2FA-F0F1C8826B7B),
	version(1.0),
]
library devicesLib
{
	importlib("stdole2.tlb");
	[
		uuid(3876DB1D-9C8A-4AD4-8A6E-B65C22003585)		
	]
	coclass Null
	{
		[default] interface INull;
	};
};

